In [109]:
import numpy as np

In [110]:
arr=np.arange(0,10)

In [111]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.array(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
coarr= arr[7:9]

In [114]:
coarr[0:2]=89

In [115]:
coarr

array([89, 89])

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, 89, 89,  9])

In [117]:
arr2=np.arange(0,36)

In [118]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [119]:
arr2=arr2.reshape(6,6)

In [120]:
arr2.shape

(6, 6)

In [121]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [122]:
arr2[0:6,2].reshape(6,1).shape

(6, 1)

In [124]:
arr2[0:3,2:5]=98

In [125]:
arr2

array([[ 0,  1, 98, 98, 98,  5],
       [ 6,  7, 98, 98, 98, 11],
       [12, 13, 98, 98, 98, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [126]:
arr2.argmax()

2

In [129]:
arr2.dtype

dtype('int32')

In [130]:
arr2>6

array([[False, False,  True,  True,  True, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [132]:
arr2[arr2>8]

array([98, 98, 98, 98, 98, 98, 11, 12, 13, 98, 98, 98, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [26]:
np.random.rand(5)

array([0.87389805, 0.61785124, 0.15488256, 0.40811395, 0.91625851])